"""annotations: support multi-point strokes and color

Revision ID: 38ae1f2a1ff1
Revises: 3bd3489a1a18
Create Date: 2026-09-05 16:29:42.503949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ae1f2a1ff1'
down_revision: Union[str, Sequence[str], None] = '3bd3489a1a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('points_json', sa.Text(), nullable=False))
    op.add_column('annotations', sa.Column('color', sa.String(length=7), nullable=False))
    op.drop_column('annotations', 'position_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('position_json', sa.TEXT(), nullable=True))
    op.drop_column('annotations', 'color')
    op.drop_column('annotations', 'points_json')
    # ### end Alembic commands ###
