"""initial imaging schema

Revision ID: 3bd3489a1a18
Revises: 
Create Date: 2026-08-29 20:45:43.369727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd3489a1a18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imaging_studies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('owner_doctor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=True),
    sa.Column('slice_count', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('asset_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imaging_studies_asset_hash'), 'imaging_studies', ['asset_hash'], unique=False)
    op.create_index(op.f('ix_imaging_studies_case_id'), 'imaging_studies', ['case_id'], unique=False)
    op.create_index(op.f('ix_imaging_studies_owner_doctor_id'), 'imaging_studies', ['owner_doctor_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('study_id', sa.String(length=36), nullable=False),
    sa.Column('position_json', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by_doctor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['imaging_studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_created_by_doctor_id'), 'annotations', ['created_by_doctor_id'], unique=False)
    op.create_index(op.f('ix_annotations_study_id'), 'annotations', ['study_id'], unique=False)
    op.create_table('imaging_series',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('study_id', sa.String(length=36), nullable=False),
    sa.Column('series_instance_uid', sa.String(length=128), nullable=True),
    sa.Column('slice_count', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('pixel_spacing_row_mm', sa.Float(), nullable=True),
    sa.Column('pixel_spacing_col_mm', sa.Float(), nullable=True),
    sa.Column('slice_spacing_mm', sa.Float(), nullable=True),
    sa.Column('orientation_reliable', sa.Boolean(), nullable=False),
    sa.Column('reconstruction_kernel', sa.String(length=64), nullable=True),
    sa.Column('hu_available', sa.Boolean(), nullable=False),
    sa.Column('fallback_ordering_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['imaging_studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imaging_series_study_id'), 'imaging_series', ['study_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('study_id', sa.String(length=36), nullable=False),
    sa.Column('measurement_type', sa.String(length=32), nullable=False),
    sa.Column('geometry_json', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('units', sa.String(length=16), nullable=False),
    sa.Column('mean_hu', sa.Float(), nullable=True),
    sa.Column('median_hu', sa.Float(), nullable=True),
    sa.Column('hu_stddev', sa.Float(), nullable=True),
    sa.Column('created_by_doctor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['imaging_studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_created_by_doctor_id'), 'measurements', ['created_by_doctor_id'], unique=False)
    op.create_index(op.f('ix_measurements_study_id'), 'measurements', ['study_id'], unique=False)
    op.create_index('ix_measurements_study_type', 'measurements', ['study_id', 'measurement_type'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('study_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=128), nullable=True),
    sa.Column('method_version', sa.String(length=32), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['imaging_studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_study_id'), 'processing_jobs', ['study_id'], unique=False)
    op.create_table('regions_of_interest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('study_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('centroid_x_mm', sa.Float(), nullable=True),
    sa.Column('centroid_y_mm', sa.Float(), nullable=True),
    sa.Column('centroid_z_mm', sa.Float(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('volume_ml', sa.Float(), nullable=True),
    sa.Column('mean_hu', sa.Float(), nullable=True),
    sa.Column('median_hu', sa.Float(), nullable=True),
    sa.Column('laterality', sa.String(length=16), nullable=True),
    sa.Column('zone', sa.String(length=32), nullable=True),
    sa.Column('created_by_doctor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['imaging_studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_of_interest_study_id'), 'regions_of_interest', ['study_id'], unique=False)
    op.create_index('ix_roi_study_source', 'regions_of_interest', ['study_id', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roi_study_source', table_name='regions_of_interest')
    op.drop_index(op.f('ix_regions_of_interest_study_id'), table_name='regions_of_interest')
    op.drop_table('regions_of_interest')
    op.drop_index(op.f('ix_processing_jobs_study_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_measurements_study_type', table_name='measurements')
    op.drop_index(op.f('ix_measurements_study_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_created_by_doctor_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_imaging_series_study_id'), table_name='imaging_series')
    op.drop_table('imaging_series')
    op.drop_index(op.f('ix_annotations_study_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_created_by_doctor_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_imaging_studies_owner_doctor_id'), table_name='imaging_studies')
    op.drop_index(op.f('ix_imaging_studies_case_id'), table_name='imaging_studies')
    op.drop_index(op.f('ix_imaging_studies_asset_hash'), table_name='imaging_studies')
    op.drop_table('imaging_studies')
    # ### end Alembic commands ###
