"""
Quantitative imaging analysis for a reconstructed chest CT study.

Turns a reconstructed HU volume plus a lung segmentation into a structured,
spatially organised set of measurements. Every value here is either read from
DICOM metadata or computed deterministically from the voxel data - nothing is
estimated, inferred, or generated by a model.

WHAT THIS MODULE DOES NOT DO
    It does not detect, classify, or name any disease or radiological finding.
    Sections that would require capabilities this application does not have
    (lobe segmentation, finding detection, airway and vessel segmentation,
    texture radiomics, prior-study registration) return an explicit
    NOT_AVAILABLE status with the reason, and never a placeholder number.

PROVENANCE
    Every section carries a `provenance` block naming where its numbers came
    from - `dicom_metadata`, `voxel_computation`, or `segmentation` - so a
    reader can tell a directly-measured quantity from one that inherits the
    segmentation's assumptions. There is currently no `model_output`
    provenance anywhere in this module, because no model is used.

UNITS
    Volumes are millilitres (1 mL = 1000 mm^3), computed from the physical
    voxel volume, never from voxel counts alone. Distances are millimetres.
    Densities are Hounsfield units.
"""

from datetime import datetime, timezone

import numpy as np
from scipy import ndimage

from density_regions import analyze_density_regions

ANALYSIS_VERSION = "1.0.0"

# Status vocabulary used throughout the result.
OK = "OK"
WARNING = "WARNING"
FAILED = "FAILED"
NOT_AVAILABLE = "NOT_AVAILABLE"
NOT_EVALUATED = "NOT_EVALUATED"

# Histogram: fixed range and bin width so histograms are directly comparable
# between studies and between regions of the same study.
HIST_MIN_HU = -1024.0
HIST_MAX_HU = 200.0
HIST_BIN_WIDTH_HU = 8.0

# Distance from the pleural surface used to define the peripheral band. This
# is a geometric convention for describing WHERE tissue sits, not a
# diagnostic threshold.
PERIPHERAL_BAND_MM = 20.0
SUBPLEURAL_BAND_MM = 10.0

PERCENTILES = (5, 10, 25, 50, 75, 90, 95)


def _now():
    return datetime.now(timezone.utc).isoformat()


def _provenance(source, method, **extra):
    p = {
        "source": source,
        "method": method,
        "analysis_version": ANALYSIS_VERSION,
        "computed_at": _now(),
    }
    p.update(extra)
    return p


def _unavailable(reason, requires=None):
    """A section that cannot be computed. Carries the reason and what it would
    take to enable it - never a number."""
    block = {"status": NOT_AVAILABLE, "reason": reason}
    if requires:
        block["requires"] = requires
    return block


# ---------------------------------------------------------------------------
# Density statistics
# ---------------------------------------------------------------------------

def hu_statistics(hu_volume, mask, voxel_volume_ml):
    """Descriptive statistics of the HU values inside `mask`.

    Definitions are the standard ones: the mean is the arithmetic mean, the
    standard deviation is the population (ddof=0) standard deviation, and
    percentiles use linear interpolation between order statistics
    (numpy's default). Skewness and kurtosis are the third and fourth
    standardised moments, with kurtosis reported as EXCESS kurtosis (normal
    distribution = 0).
    """
    values = hu_volume[mask]
    n = int(values.size)
    if n == 0:
        return {"status": NOT_AVAILABLE, "reason": "The region contains no voxels."}

    values = values.astype(np.float64, copy=False)
    mean = float(values.mean())
    std = float(values.std(ddof=0))
    pcts = np.percentile(values, PERCENTILES)

    if std > 1e-9:
        z = (values - mean) / std
        skewness = float((z ** 3).mean())
        kurtosis_excess = float((z ** 4).mean() - 3.0)
    else:
        skewness = 0.0
        kurtosis_excess = 0.0

    return {
        "status": OK,
        "voxel_count": n,
        "volume_ml": round(n * voxel_volume_ml, 2),
        "mean_hu": round(mean, 2),
        "median_hu": round(float(np.median(values)), 2),
        "std_hu": round(std, 2),
        "min_hu": round(float(values.min()), 2),
        "max_hu": round(float(values.max()), 2),
        "percentiles_hu": {f"p{p}": round(float(v), 2) for p, v in zip(PERCENTILES, pcts)},
        # First-order radiomic descriptors. These are shape-free intensity
        # statistics with standard definitions; they are NOT texture features.
        "skewness": round(skewness, 4),
        "kurtosis_excess": round(kurtosis_excess, 4),
    }


def hu_histogram(hu_volume, mask):
    """Fixed-grid histogram of HU values inside `mask`.

    The grid is identical for every region and every study
    (HIST_MIN_HU..HIST_MAX_HU at HIST_BIN_WIDTH_HU), so histograms can be
    overlaid or compared directly. Values outside the range are counted in
    the reported underflow/overflow totals rather than silently dropped.
    """
    values = hu_volume[mask]
    if values.size == 0:
        return {"status": NOT_AVAILABLE, "reason": "The region contains no voxels."}

    n_bins = int(round((HIST_MAX_HU - HIST_MIN_HU) / HIST_BIN_WIDTH_HU))
    counts, edges = np.histogram(values, bins=n_bins, range=(HIST_MIN_HU, HIST_MAX_HU))
    under = int((values < HIST_MIN_HU).sum())
    over = int((values > HIST_MAX_HU).sum())

    return {
        "status": OK,
        "bin_width_hu": HIST_BIN_WIDTH_HU,
        "range_hu": [HIST_MIN_HU, HIST_MAX_HU],
        "bin_edges_hu": [round(float(e), 2) for e in edges],
        "counts": [int(c) for c in counts],
        "underflow_count": under,
        "overflow_count": over,
        "total_voxels": int(values.size),
    }


# ---------------------------------------------------------------------------
# Spatial region decomposition
# ---------------------------------------------------------------------------

def zone_assignment_by_slice(mask, geometry):
    """Per-slice zone label, so a region's centroid can be reported by zone."""
    n_slices = mask.shape[0]
    slice_has_lung = mask.any(axis=(1, 2))
    if not slice_has_lung.any():
        return None
    z = np.array([geometry.to_world(k, 0, 0)[2] for k in range(n_slices)], dtype=np.float64)
    lung_z = z[slice_has_lung]
    z_min, z_max = float(lung_z.min()), float(lung_z.max())
    span = z_max - z_min
    if span <= 0:
        return None
    lo_cut, hi_cut = z_min + span / 3.0, z_min + 2.0 * span / 3.0
    return ["lower" if zz < lo_cut else ("middle" if zz < hi_cut else "upper") for zz in z]


def superior_inferior_zones(mask, geometry):
    """Splits the lung mask into upper / middle / lower thirds.

    The split is made along the true superior-inferior patient axis, using
    each slice's world Z coordinate rather than its array index, so a study
    stored in either slice direction produces the same anatomical zones. The
    thirds divide the lung's own Z extent into three equal spans - this is a
    geometric convention, not an anatomical lobe boundary.
    """
    n_slices = mask.shape[0]
    slice_has_lung = mask.any(axis=(1, 2))
    if not slice_has_lung.any():
        return None, {"status": NOT_AVAILABLE, "reason": "The lung mask is empty."}

    z_of_slice = np.array([geometry.to_world(k, 0, 0)[2] for k in range(n_slices)], dtype=np.float64)
    lung_z = z_of_slice[slice_has_lung]
    z_min, z_max = float(lung_z.min()), float(lung_z.max())
    span = z_max - z_min
    if span <= 0:
        return None, {"status": NOT_AVAILABLE,
                       "reason": "The lung occupies a single slice position; zones cannot be formed."}

    lower_cut = z_min + span / 3.0
    upper_cut = z_min + 2.0 * span / 3.0

    zone_of_slice = np.full(n_slices, "", dtype=object)
    for k in range(n_slices):
        z = z_of_slice[k]
        zone_of_slice[k] = "lower" if z < lower_cut else ("middle" if z < upper_cut else "upper")

    zones = {}
    for name in ("upper", "middle", "lower"):
        sel = np.array([zone_of_slice[k] == name for k in range(n_slices)])
        zm = np.zeros_like(mask)
        zm[sel] = mask[sel]
        zones[name] = zm

    meta = {
        "status": OK,
        "axis": "patient superior-inferior (world Z)",
        "lung_z_extent_mm": [round(z_min, 2), round(z_max, 2)],
        "boundaries_mm": {"lower_middle": round(lower_cut, 2), "middle_upper": round(upper_cut, 2)},
        "definition": "The lung's own Z extent divided into three equal spans.",
    }
    return zones, meta


def pleural_distance_regions(mask, spacing_mm):
    """Splits the lung mask by distance from the pleural surface.

    A Euclidean distance transform is run INSIDE the mask with the true
    physical voxel spacing, so each voxel's value is its distance in
    millimetres to the nearest non-lung voxel - i.e. to the lung boundary.
    Peripheral means within PERIPHERAL_BAND_MM of that boundary; central is
    the remainder. Subpleural is a narrower band within the peripheral one.

    This describes position only. It carries no diagnostic meaning.
    """
    if not mask.any():
        return None, {"status": NOT_AVAILABLE, "reason": "The lung mask is empty."}

    # The distance transform must measure distance to the OUTSIDE of the lung,
    # not to the nearest hole inside it. The lung mask keeps vessel and airway
    # holes: those structures connect to the hilum, so they are not enclosed
    # in 3D and survive 3D hole filling. Running the transform on the raw mask
    # therefore measures "distance to the nearest vessel", which on a real
    # study capped the depth at 21.8 mm and classified 99.98% of the lung as
    # peripheral.
    #
    # In a single axial slice, however, a vessel appears as an isolated region
    # enclosed by lung, so a per-slice 2D fill closes it. The filled envelope
    # is used only to define the boundary; every statistic is still reported
    # over the original mask.
    envelope = np.empty_like(mask)
    for k in range(mask.shape[0]):
        envelope[k] = ndimage.binary_fill_holes(mask[k])

    # sampling order must match array axes: (slice, row, column) -> (z, y, x)
    sampling = (float(spacing_mm[2]), float(spacing_mm[1]), float(spacing_mm[0]))
    dist_mm = ndimage.distance_transform_edt(envelope, sampling=sampling)

    peripheral = mask & (dist_mm <= PERIPHERAL_BAND_MM)
    central = mask & (dist_mm > PERIPHERAL_BAND_MM)
    subpleural = mask & (dist_mm <= SUBPLEURAL_BAND_MM)

    meta = {
        "status": OK,
        "peripheral_band_mm": PERIPHERAL_BAND_MM,
        "subpleural_band_mm": SUBPLEURAL_BAND_MM,
        "definition": ("Euclidean distance to the lung boundary, computed at true physical voxel "
                       "spacing on a per-slice hole-filled envelope so internal vessel and airway "
                       "holes do not act as false boundaries. Peripheral = within the band of the "
                       "pleural surface; central = deeper than the band. Positional only."),
        "max_depth_mm": round(float(dist_mm.max()), 2),
        "envelope_voxel_excess_percent": round(
            (float(envelope.sum()) - float(mask.sum())) / float(mask.sum()) * 100.0, 3),
    }
    return {"peripheral": peripheral, "central": central, "subpleural": subpleural}, meta


# ---------------------------------------------------------------------------
# Scan quality
# ---------------------------------------------------------------------------

def assess_scan_quality(summary, segmentation_stats, geometry, series_status):
    """Technical adequacy of the study for quantitative analysis.

    This is an assessment of the IMAGE, not of the patient. It never
    constitutes a clinical finding.
    """
    checks = []
    warnings = []

    def add(name, status, detail, value=None):
        checks.append({"name": name, "status": status, "detail": detail, "value": value})
        if status in (WARNING, FAILED):
            warnings.append(f"{name}: {detail}")

    slice_count = summary.get("slice_count") or 0
    add("Slice count", OK if slice_count >= 40 else WARNING,
        "Enough slices for volumetric analysis." if slice_count >= 40
        else "Few slices; volumetric and zonal measurements are coarse.", slice_count)

    add("Image dimensions", OK, "Reconstructed in-plane matrix.",
        f"{summary.get('rows')} x {summary.get('columns')}")

    ps = summary.get("pixel_spacing_mm")
    add("Pixel spacing", OK if ps else NOT_AVAILABLE,
        "Read from DICOM PixelSpacing." if ps else "PixelSpacing absent; a 1 mm fallback was used for display only.",
        ps)

    ss = summary.get("slice_spacing_mm")
    add("Slice spacing", OK if ss else NOT_AVAILABLE,
        "Median inter-slice spacing." if ss else "Could not be determined.",
        round(ss, 3) if ss else None)

    st = summary.get("slice_thickness_mm")
    add("Slice thickness", OK if st is not None else NOT_AVAILABLE,
        "Read from DICOM SliceThickness." if st is not None else "SliceThickness absent from the series.", st)

    hu_status = summary.get("hu_conversion_status")
    add("Hounsfield calibration", OK if hu_status == "AVAILABLE" else (
            WARNING if hu_status == "PARTIAL" else FAILED),
        {"AVAILABLE": "Rescale slope and intercept present on every slice.",
         "PARTIAL": "Some slices lack rescale values; density measurements exclude nothing but are less reliable.",
         }.get(hu_status, "No calibrated Hounsfield data; density measurements are not meaningful."),
        hu_status)

    ori = summary.get("orientation_status", "")
    add("Image orientation", OK if ori == "AVAILABLE" else WARNING,
        "Slice order derived from patient geometry." if ori == "AVAILABLE"
        else "Fallback slice ordering was used; spatial measurements are less reliable.", ori)

    scanner = summary.get("scanner_metadata") or {}
    add("Scanner", OK if scanner else NOT_AVAILABLE,
        "Non-identifying technical metadata present."
        if scanner else "No technical scanner metadata available.",
        scanner or None)

    add("Reconstruction kernel", NOT_AVAILABLE,
        "ConvolutionKernel is not among the technical fields this application reads.", None)

    add("Contrast status", NOT_AVAILABLE,
        "Determining contrast requires metadata this application does not read, "
        "and inferring it from density alone is unreliable.", None)

    irregular = any("Irregular spacing" in w for w in (summary.get("validation_warnings") or []))
    gap = any("large gap" in w.lower() for w in (summary.get("validation_warnings") or []))
    add("Slice spacing regularity", WARNING if (irregular or gap) else OK,
        "Irregular spacing or a large inter-slice gap was detected; volumes assume uniform spacing."
        if (irregular or gap) else "Spacing is regular within tolerance.", None)

    dup = any("duplicate" in w.lower() for w in (summary.get("validation_warnings") or []))
    add("Duplicate slices", WARNING if dup else OK,
        "Duplicate SOPInstanceUIDs were dropped during validation." if dup
        else "No duplicate instances detected.", None)

    if segmentation_stats:
        touches_border = segmentation_stats.get("touches_inplane_border")
        add("Lung containment (in plane)", WARNING if touches_border else OK,
            "The lung mask reaches the edge of the field of view; the thorax may be clipped."
            if touches_border else "The lung mask lies fully inside the field of view.", None)

        truncated = segmentation_stats.get("touches_scan_range_start_or_end")
        add("Lung containment (scan range)", WARNING if truncated else OK,
            "Lung tissue reaches the first or last slice; the lungs may not be fully covered, "
            "so total volume may be underestimated." if truncated
            else "Lung tissue does not reach either end of the scan range.", None)
    else:
        add("Lung containment", NOT_EVALUATED, "Segmentation has not been run for this study.", None)

    add("Motion / artifact", NOT_EVALUATED,
        "No motion or streak-artifact metric is implemented. Not assessed rather than assumed absent.", None)

    statuses = [c["status"] for c in checks]
    if FAILED in statuses:
        overall = FAILED
    elif WARNING in statuses:
        overall = WARNING
    else:
        overall = OK

    suitable = overall != FAILED and hu_status in ("AVAILABLE", "PARTIAL")

    return {
        "status": overall,
        "suitable_for_quantitative_analysis": bool(suitable),
        "checks": checks,
        "warnings": warnings,
        "note": ("A technical assessment of the image only. It is not a clinical finding and says "
                 "nothing about the patient."),
        "provenance": _provenance("dicom_metadata", "Validation results and DICOM technical fields."),
    }


# ---------------------------------------------------------------------------
# Top-level analysis
# ---------------------------------------------------------------------------

def analyze_study(hu_volume, hu_available_per_slice, geometry, segmentation, summary,
                   series_status="PASS"):
    """Builds the full structured analysis for one study.

    `segmentation` may be None (not yet run) or a failed result - in that
    case every anatomy-dependent section reports NOT_AVAILABLE with the
    reason, and only scan quality is produced.
    """
    spacing = geometry.spacing_mm
    voxel_volume_mm3 = float(spacing[0]) * float(spacing[1]) * float(spacing[2])
    voxel_volume_ml = voxel_volume_mm3 / 1000.0

    seg_ok = segmentation is not None and getattr(segmentation, "success", False)
    seg_stats = dict(getattr(segmentation, "stats", {})) if segmentation is not None else {}

    result = {
        "analysis_version": ANALYSIS_VERSION,
        "generated_at": _now(),
        "voxel_volume_mm3": round(voxel_volume_mm3, 6),
        "spacing_mm": [round(float(v), 4) for v in spacing],
        "scan_quality": assess_scan_quality(summary, seg_stats if seg_ok else None,
                                             geometry, series_status),
        "warnings": [],
    }

    if not seg_ok:
        reason = ("Lung segmentation has not been run for this study."
                  if segmentation is None else
                  "Lung segmentation did not pass its plausibility checks, so no anatomy-dependent "
                  "measurement can be trusted.")
        for key in ("lung_metrics", "density_metrics", "histogram", "regional_metrics",
                     "asymmetry", "lobe_metrics", "findings", "airways", "vasculature",
                     "longitudinal"):
            result[key] = _unavailable(reason, requires="A successful lung segmentation.")
        result["warnings"].append(reason)
        return result

    mask = segmentation.mask
    left = segmentation.left_mask
    right = segmentation.right_mask
    has_sides = left is not None and right is not None

    # ---- 2. total lung quantification ----
    total_voxels = int(mask.sum())
    total_ml = total_voxels * voxel_volume_ml
    lung_metrics = {
        "status": OK,
        "total_lung_volume_ml": round(total_ml, 1),
        "voxel_count": total_voxels,
        "left_lung_volume_ml": round(float(left.sum()) * voxel_volume_ml, 1) if has_sides else None,
        "right_lung_volume_ml": round(float(right.sum()) * voxel_volume_ml, 1) if has_sides else None,
        "left_right_available": bool(has_sides),
        "left_right_method": seg_stats.get("left_right_method"),
        "volume_definition": "voxel count x (x spacing x y spacing x z spacing), converted to mL.",
        "provenance": _provenance("segmentation", "Voxel count within the lung mask scaled by "
                                                   "physical voxel volume.",
                                   segmentation_method=segmentation.method,
                                   segmentation_method_version=segmentation.method_version),
    }
    if has_sides:
        lv = lung_metrics["left_lung_volume_ml"]
        rv = lung_metrics["right_lung_volume_ml"]
        lung_metrics["left_fraction"] = round(lv / total_ml, 4) if total_ml else None
        lung_metrics["right_fraction"] = round(rv / total_ml, 4) if total_ml else None
        lung_metrics["left_right_ratio"] = round(lv / rv, 4) if rv else None
    result["lung_metrics"] = lung_metrics

    # ---- 4. density analysis ----
    density = {
        "status": OK,
        "whole_lungs": hu_statistics(hu_volume, mask, voxel_volume_ml),
        "provenance": _provenance("voxel_computation",
                                   "Descriptive statistics of HU values inside the segmentation mask.",
                                   percentiles=list(PERCENTILES),
                                   percentile_method="numpy linear interpolation",
                                   std_ddof=0, kurtosis="excess (normal = 0)"),
    }
    if has_sides:
        density["left_lung"] = hu_statistics(hu_volume, left, voxel_volume_ml)
        density["right_lung"] = hu_statistics(hu_volume, right, voxel_volume_ml)
    result["density_metrics"] = density

    histograms = {"whole_lungs": hu_histogram(hu_volume, mask)}
    if has_sides:
        histograms["left_lung"] = hu_histogram(hu_volume, left)
        histograms["right_lung"] = hu_histogram(hu_volume, right)
    result["histogram"] = {
        "status": OK,
        "regions": histograms,
        "provenance": _provenance("voxel_computation",
                                   "Fixed-grid histogram so regions and studies are directly comparable.",
                                   bin_width_hu=HIST_BIN_WIDTH_HU, range_hu=[HIST_MIN_HU, HIST_MAX_HU]),
    }

    # ---- 5. regional distribution ----
    regional = {"status": OK,
                "provenance": _provenance("voxel_computation",
                                           "Geometric decomposition of the lung mask; positional only.")}

    zones, zone_meta = superior_inferior_zones(mask, geometry)
    if zones is None:
        regional["zones"] = zone_meta
    else:
        zdata = {}
        for name, zmask in zones.items():
            vox = int(zmask.sum())
            zdata[name] = {
                "volume_ml": round(vox * voxel_volume_ml, 1),
                "percent_of_lung": round(vox / total_voxels * 100.0, 2) if total_voxels else None,
                "density": hu_statistics(hu_volume, zmask, voxel_volume_ml),
            }
        regional["zones"] = {"status": OK, "definition": zone_meta, "regions": zdata}

    bands, band_meta = pleural_distance_regions(mask, spacing)
    if bands is None:
        regional["pleural_bands"] = band_meta
    else:
        bdata = {}
        for name, bmask in bands.items():
            vox = int(bmask.sum())
            bdata[name] = {
                "volume_ml": round(vox * voxel_volume_ml, 1),
                "percent_of_lung": round(vox / total_voxels * 100.0, 2) if total_voxels else None,
                "density": hu_statistics(hu_volume, bmask, voxel_volume_ml),
            }
        regional["pleural_bands"] = {"status": OK, "definition": band_meta, "regions": bdata}
    result["regional_metrics"] = regional

    # ---- 6. left/right asymmetry ----
    if has_sides:
        lv = float(left.sum()) * voxel_volume_ml
        rv = float(right.sum()) * voxel_volume_ml
        lmean = density["left_lung"].get("mean_hu")
        rmean = density["right_lung"].get("mean_hu")
        denom = lv + rv
        vol_index = (lv - rv) / denom if denom else None
        result["asymmetry"] = {
            "status": OK,
            "volume_asymmetry_index": round(vol_index, 4) if vol_index is not None else None,
            "volume_asymmetry_definition": ("(left - right) / (left + right). Zero is symmetric; "
                                             "positive means the left lung is larger. Bounded to [-1, 1]. "
                                             "This is a descriptive geometric ratio, not a clinical score."),
            "mean_hu_difference": (round(lmean - rmean, 2)
                                    if lmean is not None and rmean is not None else None),
            "mean_hu_difference_definition": "left mean HU minus right mean HU, in Hounsfield units.",
            "caveat": (seg_stats.get("left_right_method") == "sagittal_midline_split") and
                      ("Left and right were divided at the sagittal midline because the lungs form a "
                       "single connected region. Per-side values near the mediastinum are approximate.")
                      or None,
            "provenance": _provenance("segmentation", "Derived from per-side masks and their HU statistics."),
        }
    else:
        result["asymmetry"] = _unavailable(
            "Left and right lungs were not separated for this study.",
            requires="Reliable image orientation and a separable lung mask.")

    # ---- 7/9. quantitative densitometry + located regions ----
    # Density measurements with published cut-points, clustered so each one
    # can be found in the source CT. These are measurements, not findings -
    # see density_regions.py for the distinction and the threshold sources.
    try:
        zone_masks = zones if zones is not None else None
        zone_by_slice = zone_assignment_by_slice(mask, geometry)
        dist_for_regions = None
        if bands is not None:
            sampling = (float(spacing[2]), float(spacing[1]), float(spacing[0]))
            envelope = np.empty_like(mask)
            for k in range(mask.shape[0]):
                envelope[k] = ndimage.binary_fill_holes(mask[k])
            dist_for_regions = ndimage.distance_transform_edt(envelope, sampling=sampling)

        result["densitometry"] = analyze_density_regions(
            hu_volume, mask, geometry, voxel_volume_ml,
            left_mask=left, right_mask=right,
            zones=zone_masks, zone_of_slice=zone_by_slice, dist_mm=dist_for_regions,
        )
    except Exception as exc:  # noqa: BLE001
        result["densitometry"] = _unavailable(
            f"Densitometry could not be computed: {exc}",
            requires="A valid lung segmentation and calibrated Hounsfield data.")

    # ---- sections requiring capabilities this application does not have ----
    result["lobe_metrics"] = _unavailable(
        "No lobe segmentation is implemented. The five pulmonary lobes cannot be delineated by "
        "the HU-threshold method used here, because the fissures are not reliably resolvable by "
        "density alone. Reporting lobe volumes without segmenting lobes would be fabrication.",
        requires="A fissure-aware or model-based lobe segmentation.")

    result["findings"] = {
        "status": NOT_AVAILABLE,
        "reason": ("No finding-detection method is implemented. This application performs no disease "
                   "classification and detects no radiological findings."),
        "requires": "A validated detection or segmentation model for each finding type.",
        # Structure only, so the viewer and API contract are stable when a real
        # detector is added. Deliberately empty - never populated with examples.
        "supported_finding_types": [
            "ground_glass_opacity", "reticulation", "honeycombing", "traction_bronchiectasis",
            "mosaic_attenuation", "air_trapping", "consolidation", "emphysema",
            "cystic_change", "nodule", "architectural_distortion",
        ],
        "regions": [],
        "burden": {},
    }

    result["airways"] = _unavailable(
        "No airway segmentation is implemented. Airway lumen, wall thickness, and branch "
        "generation are not measured.",
        requires="An airway-tree segmentation with wall detection.")

    result["vasculature"] = _unavailable(
        "No vessel segmentation is implemented. Vessel volume, diameter, and regional density "
        "are not measured.",
        requires="A pulmonary vessel segmentation.")

    result["texture_radiomics"] = {
        "status": WARNING,
        "note": ("First-order intensity statistics (mean, variance, skewness, excess kurtosis, "
                 "percentiles) are computed and appear under density metrics. Texture matrix "
                 "families are not implemented."),
        "first_order": OK,
        "glcm": NOT_AVAILABLE, "glrlm": NOT_AVAILABLE, "glszm": NOT_AVAILABLE,
        "ngtdm": NOT_AVAILABLE, "gldm": NOT_AVAILABLE,
        "shape_features": NOT_AVAILABLE,
        "requires": "A documented, reproducible texture-feature implementation with recorded "
                    "resampling and binning parameters.",
    }

    result["longitudinal"] = _unavailable(
        "Comparison with a prior study is not implemented. No spatial registration exists, and "
        "comparing studies by slice index would be misleading.",
        requires="Deformable or rigid registration between studies, with a registration-quality metric.")

    result["provenance_summary"] = {
        "analysis_version": ANALYSIS_VERSION,
        "segmentation_method": segmentation.method,
        "segmentation_method_version": segmentation.method_version,
        "model_derived_values": "none",
        "note": ("No machine-learning model contributed to any value in this report. Every number "
                 "is read from DICOM metadata or computed deterministically from voxel data."),
    }
    result["warnings"].extend(segmentation.warnings)
    return result
